import Header from '@components/Header';
import ReactQueryProviders from '@components/react-query/ReactQueryProviders';
import { Theme, ThemePanel } from '@radix-ui/themes';
import '@styles/globals.css';

import { ReactNode } from 'react';

export const metadata = {
  title: 'samik beach',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Theme
          accentColor="crimson"
          grayColor="sand"
          radius="large"
          panelBackground="solid"
        >
          <ReactQueryProviders>
            <Header />
            {children}
          </ReactQueryProviders>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
