name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.x'

      - name: Build
        run: yarn run build

      - name: Semantic Release
        run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
